{
 "title": "Kios",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lenteng Agung",
   "type": "logs",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{topic=~\"vm/312281470C3/pub|vm/312281470C3/sub\"}"
    }
   ]
  },
  {
   "title": "Get Proximity Kalimalang",
   "type": "cloudspout-button-panel",
   "description": "Get Proximity Kalimalang",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"loki-mqtt\"}"
    }
   ]
  },
  {
   "title": "Kalimalang",
   "type": "logs",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "{topic=~\"vm/31110470C1/pub|vm/31110470C1/sub\"}"
    }
   ]
  },
  {
   "title": "Bintaro",
   "type": "logs",
   "description": "Log kios bintaro",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{topic=~\"vm/312281460C2/pub|vm/312281460C2/sub\"}"
    }
   ]
  },
  {
   "title": "BSD",
   "type": "logs",
   "description": "Log kios Bsd",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "{topic=~\"vm/31110310C1/pub|vm/31110310C1/sub\"}"
    }
   ]
  },
  {
   "title": "All Transaksi",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{topic=\"vm/token/sub\"}"
    }
   ]
  }
 ]
}