version: "0.1"

services: 
  grafana:
    image: grafana/grafana:8.2.3
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    links:
      - loki-mqtt
      - loki-cs

  loki-mqtt:
    image:  grafana/loki:2.3.0
    volumes:
      - ./config/:/mnt/config
    entrypoint:
      - /usr/bin/loki
      - -config.file=/mnt/config/loki-config-mqtt.yaml
    ports:
      - "3101:3101"
  
  loki-cs:
    image:  grafana/loki:2.3.0
    volumes:
      - ./config/:/mnt/config
    entrypoint:
      - /usr/bin/loki
      - -config.file=/mnt/config/loki-config-cs.yaml
    ports:
      - "3102:3102"

  paho-listener:
    build: ./paho-listener
    links:
      - loki-mqtt