apiVersion: 1

deleteDatasources:
  - name: prometheus

datasources:
  - name: prome
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
