version: "3.7"

services: 
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    links:
      - loki-mqtt
      - loki-cs
      - prometheus

  prometheus:
    image: prom/prometheus:main
    volumes:
      - ./provisioning/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:master
    ports:
      - "9100:9100"

  loki-mqtt:
    image:  grafana/loki:2.3.0
    volumes:
      - ./config/:/mnt/config
    entrypoint:
      - /usr/bin/loki
      - -config.file=/mnt/config/loki-config-mqtt.yaml
    ports:
      - "3101:3101"
  
  loki-cs:
    image:  grafana/loki:2.3.0
    volumes:
      - ./config/:/mnt/config
    entrypoint:
      - /usr/bin/loki
      - -config.file=/mnt/config/loki-config-cs.yaml
    ports:
      - "3102:3102"

  paho-listener:
    build: ./paho-listener
    links:
      - loki-mqtt